#!/usr/bin/python
#
# Copyright (C) 2005 - 2010, TUBITAK/UEKAE
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Please read the COPYING file.
#

import sys
import errno
import traceback
import exceptions
import signal

import evoio
import evoio.context as ctx
import evoio.cli.evoiocli as evoiocli

import gettext
gettext.bindtextdomain('evoio', "/usr/share/locale")
gettext.textdomain('evoio')
__trans = gettext.translation('evoio', fallback=True)
_ = __trans.ugettext

def sig_handler(sig, frame):
    if sig == signal.SIGTERM:
        exit()

def exit():
    sys.exit(1)

def handle_exception(exception, value, tb):
    signal.signal(signal.SIGINT, signal.SIG_IGN)   # disable further interrupts
    ui = evoio.cli.CLI() # make a temporary UI
    show_traceback = False

    if exception == exceptions.KeyboardInterrupt:
        ui.error(_("Keyboard Interrupt: Exiting..."))
        exit()
    elif isinstance(value, evoio.Error):
        ui.error(_("Program terminated."))
    elif isinstance(value, evoio.Exception):
        show_traceback = True
        ui.error(_("Unhandled internal exception.\n"
                   "Please file a bug report to <http://bugs.pardus.org.tr>."))
    elif isinstance(value, IOError) and value.errno == errno.EPIPE:
        # Ignore broken pipe errors
        sys.exit(0)
    else:
        # For any other exception (possibly Python exceptions) show
        # the traceback!
        show_traceback = ctx.get_option('debug')
        ui.error(_("System error. Program terminated."))

    if show_traceback:
        ui.error("%s: %s" % (exception, str(value)))
    else:
        msg = str(value)
        if msg:
            ui.error(msg)

    ui.info(_("Please use 'io help' for general help."))

    if show_traceback:
        ui.info(_("\nTraceback:"))
        traceback.print_tb(tb)
    elif not isinstance(value, evoio.Error):
        ui.info(_("Use --debug to see a traceback."))

    exit()

if __name__ == "__main__":
    sys.excepthook = handle_exception

    signal.signal(signal.SIGTERM, sig_handler)

    cli = evoiocli.EvoioCLI()
    cli.run_command()
